name: Production Deployment

on:
  push:
    branches:
      - "main"


jobs:
  android_ios_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.4'
    - run: flutter pub get
      # build android
    - run: flutter build apk
    - run: flutter build appbundle
      # build ios
    - run: flutter build ipa --release --no-codesign

    